name: video_player_header_example
description: Demonstrates how to use the video_player_header plugin.

dependencies:
  flutter:
    sdk: flutter
  video_player_header_c_b:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
   - assets/flutter-mark-square-64.png
   - assets/Butterfly-209.mp4
